[ADD] base.group_portal for external users
Therp/Therp-Addons pull request #110
Opened 2019-09-10 08:07 UTC by ntsirintanis

2019-09-10 08:55 UTC, ntsirintanis commented
@hbrunn

2019-10-28 13:17 UTC, NL66278 commented on trp_external_user/security/res_groups.xml
> +                name="implied_ids"
Correct indentation

2019-10-28 13:19 UTC, NL66278 requested changes
Mostly OK, but needs improved indentation

2019-10-29 09:04 UTC, ntsirintanis commented
@NL66278 it is now green.

2020-03-12 09:38 UTC, NL66278 approved these changes
:+1: LGTM

2020-03-12 09:38 UTC, merged