Add module trp_project_scrum
Therp/Therp-Addons pull request #64
Opened 2017-04-12 17:15 UTC by gfcapalbo

2017-04-12 18:58 UTC, hbrunn requested changes

2017-04-12 18:58 UTC, hbrunn commented on trp_project_scrum/README.md
> +Option 2:
we don't have two options any more

2017-04-12 18:58 UTC, hbrunn commented on trp_project_scrum/README.md
> +trp_project_scrum
use the content of the name key from the manifest here

2017-04-12 18:58 UTC, hbrunn commented on trp_project_scrum/__openerp__.py
>      "version": "1.0",
remove description key and update version to oca standards

2017-04-12 18:58 UTC, hbrunn commented on trp_project_scrum/models/project_task_work.py
> +        )
you can save this search by counting `user.employee_ids` instead

2017-04-12 18:58 UTC, hbrunn commented on trp_project_scrum/security/ir_rules_collaborators_followers.xml
> +        <record id="project_task_type_rule_foll" model="ir.rule">
shouldn't you force some domain here?

2017-04-12 18:58 UTC, hbrunn commented on trp_project_scrum/security/ir_rules_collaborators_followers.xml
> +            <field name="global" eval="False" />
it's not so interesting to set this one: https://github.com/OCA/OCB/blob/8.0/openerp/addons/base/ir/ir_rule.py#L78, https://github.com/OCA/OCB/blob/8.0/openerp/addons/base/ir/ir_rule.py#L61

2017-04-12 18:58 UTC, hbrunn commented on trp_project_scrum/security/ir_rules_collaborators_followers.xml
> +        <record id="project_task_type_rule_foll" model="ir.rule">
but i consider task types harmless, so this doesn't really need a restriction imho

2017-04-12 18:58 UTC, hbrunn commented on trp_project_scrum/security/ir_rules_collaborators_followers.xml
> +                [('project_id.message_follower_ids', 'in', [user.partner_id.id])]</field>
it's not coherent to assert `use_scrum` above and not here (for my taste, we shouldn't do it anywhere. why not allow to use this module to collaborate on non-scrum-projects?)

2017-04-12 18:58 UTC, hbrunn commented on trp_project_scrum/security/ir_rules_collaborators_followers.xml
> +        <record id="actors_rule_foll" model="ir.rule">
also here, `domain_force` is missing. and also here, i think we don't really need to restrict this

2017-04-12 18:58 UTC, hbrunn commented on trp_project_scrum/tests/test_trp_project_scrum.py
> +            ).with_context(mail_notrack=True).write, {'name': 'this is not ok'}
this works, but is a bit clumsy. The context manager version is a lot simpler to write and read i think:

```python
with self.assertRaises(AccessError):
    self.task5.sudo(self.collaborator_follower.id)\
        .with_context(mail_notrack=True)\
        .write({'name': 'this is not ok'})
```

(nice writeup about context managers here: https://jeffknupp.com/blog/2016/03/07/python-with-context-managers/)

2017-04-19 08:08 UTC, gfcapalbo commented on trp_project_scrum/security/ir_rules_collaborators_followers.xml
> +                [('project_id.message_follower_ids', 'in', [user.partner_id.id])]</field>
I can take away the scrum everywhere

2017-04-19 08:14 UTC, gfcapalbo commented on trp_project_scrum/security/ir_rules_collaborators_followers.xml
> +        <record id="actors_rule_foll" model="ir.rule">
There cannot be domain force because actors have no relation with anything. I agree the rule is useless. gone/

2017-04-20 15:40 UTC, merged