11.0 mig l10n nl autoinstall
Therp/Therp-Addons pull request #87
Opened 2018-11-23 12:29 UTC by daramousk

2018-11-29 14:36 UTC, daramousk commented
@hbrunn Travis crashes for some reason.

2018-11-29 15:31 UTC, hbrunn commented
we're using an outdated `.travis.yml` here - get https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml and change what needs changing, add this as a separate commit please

2018-11-30 14:40 UTC, hbrunn requested changes

2018-11-30 14:40 UTC, hbrunn commented on l10n_nl_autoinstall/__manifest__.py
> +    "author": "Therp BV,Odoo Community Association (OCA)",
in this repo, it's actually ours

2018-11-30 14:41 UTC, hbrunn commented on l10n_nl_autoinstall/__manifest__.py
> +    "version": "11.0.0.0.0",
standard version number should be `11.0.1.0.0`

2018-12-05 16:54 UTC, daramousk commented
@hbrunn Fixed, I would appreciate this merged when possible because I need travis to work.

2018-12-06 15:41 UTC, hbrunn approved these changes

2018-12-06 15:41 UTC, merged